name: localsend_app
description: An open source cross-platform alternative to AirDrop
homepage: https://localsend.org/
publish_to: "none"

version: 1.14.0+45

environment:
  flutter: ">=3.13.0"
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_group_directory: 2.0.0
  basic_utils: 5.7.0
  collection: ^1.17.2 # allow newer versions, so it can compile with newer Flutter versions
  common:
    path: ../common
  connectivity_plus: ^6.0.3
  dart_mappable: ^4.2.2
  desktop_drop: 0.4.4
  device_apps: 2.2.0
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dynamic_color: ^1.7.0
  file_picker: ^8.0.3
  file_selector: 1.0.3
  flutter:
    sdk: flutter
  flutter_displaymode: 0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  gal: 2.3.0
  image_picker: ^1.1.1
  in_app_purchase: ^3.2.0 # [FOSS_REMOVE]
  intl: ^0.18.0 # allow newer versions, so it can compile with newer Flutter versions
  launch_at_startup: ^0.3.0
  legalize: ^1.2.2
  logging: 1.2.0
  macos_dock_progress: ^1.0.0
  mime: ^1.0.5
  network_info_plus: ^5.0.3
  open_filex: 4.4.0
  package_info_plus: ^8.0.0
  pasteboard: ^0.2.0
  path: 1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pretty_qr_code: ^3.3.0
  refena_flutter: 2.0.0
  refena_inspector_client: 2.0.0
  routerino: 0.8.0
  saf_stream: 0.4.0 # Saving files to SD card for Android <11
  screen_retriever: 0.1.9
  share_handler: ^0.0.21
  share_handler_ios: ^0.0.14 # Keep iOS <14 support
  shared_preferences: ^2.2.3
  shared_preferences_platform_interface: any
  shared_storage: 0.8.1
  shelf: 1.4.1
  shelf_router: 1.1.4
  slang: 3.31.0
  slang_flutter: 3.31.0
  system_settings: 2.1.0
  tray_manager: ^0.2.3
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  wakelock_plus: ^1.2.5
  wechat_assets_picker: ^9.0.3
  window_manager: ^0.3.9
  windows_taskbar: 1.1.2
  yaru: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  dart_mappable_builder: ^4.2.3
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^4.0.0
  mockito: 5.4.4
  msix: 3.16.7
  refena_inspector: 2.0.0
  slang_build_runner: 3.31.0
  slang_gpt: ^0.10.1
  test: ^1.24.3

dependency_overrides:
  permission_handler_windows:
    # Remove windows support as it causes trouble with Windows 7
    # https://github.com/Baseflow/flutter-permission-handler/issues/1034
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git
      ref: 2dadd8afbf81e0e3e4791d7144e689555e58f649

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/web/
    - assets/CHANGELOG.md

flutter_gen:
  line_length: 150

msix_config:
  display_name: LocalSend
  publisher_display_name: Tien Do Nam
  # Using third-party CA for now (see: https://github.com/localsend/localsend/issues/220)
  # publisher: CN=0A8E9755-183F-4F0B-823F-1B8C991D7B97
  identity_name: 11157TienDoNam.LocalSend
  logo_path: assets\img\logo-512.png
  architecture: x64
  languages: en, ar, bn, cs, da, de, el, es-ES, eu, fa, fr, he, hu, in, it, ja, ko, ne, nl, pl, pt-BR, ru, sv, th, tr, uk, vi, zh-CN, zh-HK, zh-TW

  # https://github.com/localsend/localsend/issues/398
  os_min_version: 10.0.19041.0

  startup_task:
    task_id: localsend
    enabled: false
    parameters: autostart
